# Generated by Django 4.0.2 on 2022-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emplogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('passportid', models.CharField(max_length=40)),
                ('mofano', models.CharField(max_length=40)),
                ('visano', models.IntegerField()),
                ('visastatus', models.CharField(max_length=100)),
                ('authorised', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emplogin',
            },
        ),
    ]
